### ISSUE TITLE
Bitcoin disappeared

### ISSUE THREAD

**Issue by jrcriz** [asgardex/asgard-exchange#402]
I sent 0.02517365 BTC to my wallet on 5/27/21. I bought 19.146 Rune on 5/32/21 and the remaining Bitcoin in my wallet has disappeared. How do I recover?

**Comment by stuartwk** [comment]
Hey @jrcriz, could you share your BTC or RUNE address associated with the transaction so we can take a look at what the issue might be?

**Comment by glenhodler** [comment]
Hi, similar problem - bitcoin asset showing as 0 in asgardex, since yesterday, was visible about a week ago. Shows up on thorswap when wallet is connected. Have checked blockchain - BTC is there.

**Comment by jrcriz** [comment]
bc1qm2vymp53rp5vz3h95p7m6xz5ajfqslltcll7tl

**Comment by stuartwk** [comment]
Are you using the web app or the desktop app?
There was an issue with BTC XChain, a fix was pushed and merged in from yesterday. Are you still hitting this issue?

**Comment by jrcriz** [comment]
I'm using the desktop app. Still having issues.

Jarred Curry

"You see an eyesore, we see an opportunity"
Senior Acquisition Associate | NetWorth Realty of San Diego, Inc.
5030 Camino de la Siesta, Suite 403
San Diego, CA 92108
M: 858.876.2116
REALTOR® 02015670

**Comment by jrcriz** [comment]
Very disappointed because I wanted to buy rune at $9 but now it's at $10.
Very inconvenient.

Jarred Curry

"You see an eyesore, we see an opportunity"
Senior Acquisition Associate | NetWorth Realty of San Diego, Inc.
5030 Camino de la Siesta, Suite 403
San Diego, CA 92108
M: 858.876.2116
REALTOR® 02015670

**Comment by stuartwk** [comment]
@jrcriz, this is the repo for the web app. The desktop app is a different team and codebase. You can find the desktop app repo at https://github.com/thorchain/asgardex-electron.

It looks like they just pushed a hotfix for their desktop app.

**Comment by norepetitivebeats** [comment]
I have the same issue, but the latest hotfixs doesn't solve it.

**Comment by norepetitivebeats** [comment]
I have raised this issue in the desktop repo https://github.com/thorchain/asgardex-electron/issues/1535

**Comment by jrcriz** [comment]
The new update has fixed the issue. Thanks for the help.
